apiVersion: batch/v1
kind: Job
metadata:
  generateName: rails-db-reset-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    app.kubernetes.io/instance: tutordash
spec:
  template:
    spec:
      containers:
      - name: db-reset-container
        image: your-registry/your-rails-app-image:latest
        command: ["/bin/bash", "-c"]
        args:
          # Use the fully constructed DATABASE_URL variable in the execution path.
          - "set -e; export DATABASE_URL='postgres://$(PGUSER):$(PGPASSWORD)@postgres-svc:5432/tutordash_production'; DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bundle exec rails db:reset"
          
        env:
          # --- Environment Variables setup ---
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: DB_USER
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: DB_PASS
          - name: DATABASE_URL
            value: postgres://$(PGUSER):$(PGPASSWORD)@postgres-svc:5432/tutordash_production
            
      restartPolicy: Never
  backoffLimit: 0
