apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutordash
spec:
  replicas: 2 # Run 2 copies for reliability
  selector:
    matchLabels:
      app: tutordash
  template:
    metadata:
      labels:
        app: tutordash
    spec:
      containers:
      - name: app
        # !! THIS LINE GETS UPDATED BY GITHUB ACTIONS !!
        image: ghcr.io/skg17/tutordash2:latest # Placeholder image
        env:
        - name: RAILS_ENV
          value: production # Ensure the environment is set correctly
        - name: SECRET_KEY_BASE # Inject the required variable
          valueFrom:
            secretKeyRef:
              name: rails-secret-key # The name of the Secret created in Step B
              key: SECRET_KEY_BASE
        ports:
        - containerPort: 3000
        - name: app
          # !! THIS LINE GETS UPDATED BY GITHUB ACTIONS !!
          image: ghcr.io/skg17/tutordash2:latest # Placeholder image
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-login-secret
