name: Build and Deploy to Homelab

on:
  push:
    branches: [ main ] # Trigger this workflow on pushes to the main branch

jobs:
  build-and-update-manifest:
    runs-on: self-hosted # IMPORTANT: Tells GitHub to use YOUR runner!

    permissions:
      contents: write # Allows pushing the updated manifest
      packages: write # Allows pushing the image to ghcr

    steps:
      - name: Configure SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          # Use the private key stored as a repository secret
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
          # This sets up the SSH environment for the subsequent Git push
          
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # Use the SSH URL for cloning
          repository: skg17/tutordash2 # Explicitly define the repository path
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }} # Authenticate checkout using the key
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Provided automatically by GitHub

      - name: Run RuboCop
        # Run RuboCop to make safe corrections only
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rubocop -a

      - name: Review RuboCop Results
        uses: reviewdog/action-rubocop@v2
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
      
      - name: Commit and Push Fixed Files
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'actions@github.com'
          
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Auto-fix style issues with RuboCop"

            echo "Lint fixes commited locally."
          else
            echo "No styling issues found."
          fi

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: . # Assumes Dockerfile is in the root
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest

      - name: Update Kubernetes Image Tag to SHA
        run: |
          # Set the image to the newly pushed :latest tag
          NEW_TAG="ghcr.io/${{ github.repository }}:${{ github.sha }}"
          sed -i "s|image: .*|image: $NEW_TAG|g" k8s/deployment.yaml

          echo "Manifest updated to image: $NEW_TAG"

      - name: Commit and push manifest changes
        run: |
          # Configure identity
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          git add k8s/deployment.yaml
          
          if git diff --staged --quiet; then
            echo "No manifest changes detected. Skipping commit."
            exit 0
          fi
          
          # Change commit message to reflect the SHA
          git commit --amend -m "CI: Deploy image ${{ github.sha_short }}, incorporating auto-style fixes." || \
          git commit -m "CI: Deploy image ${{ github.sha_short }}" 
          
          # Use the SSH protocol URL
          GIT_URL="https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push $GIT_URL HEAD:main