name: RuboCop Lint Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger if needed

jobs:
  rubocop:
    runs-on: self-hosted

    permissions:
      contents: write # Allows pushing the updated manifest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - name: Run RuboCop
        # Run RuboCop to make safe corrections only
        run: bundle exec rubocop -a

      # Optional: Post the results as a comment/annotation if it fails (requires an action)
      - name: Review RuboCop Results
        uses: reviewdog/action-rubocop@v2
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
      
      - name: Commit and Push Fixed Files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name 'GitHub Actions Bot'
            git config user.email 'actions@github.com'
            git add .
            git commit -m "Auto-fix style issues with RuboCop"
            git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}
          else
            echo "No styling issues found. Code style is good!"
          fi